Repository ker0olos/fable, pull requests merged in 2023-08, with the labels that each got.

#227 Create es-ES.json
  .github/workflows/deno.yml
  .github/workflows/discord.yml
  .github/workflows/fauna.yml
  __snapshots__/update_commands.test.ts.snap
  i18n/es-ES.json
  update_commands.ts
Labels: qol, i18n

#228 fix spanish not being applied
  src/i18n.ts
Labels: hotfix

#231 Stats
  __snapshots__/update_commands.test.ts.snap
  i18n/en-US.json
  i18n/es-ES.json
  models/__snapshots__/set_character_stats.test.ts.snap
  models/add_character_to_inventory.ts
  models/resolvers.gql
  models/schema.gql
  models/set_character_stats.test.ts
  models/set_character_stats.ts
  src/battle.ts
  src/discord.ts
  src/help.ts
  src/interactions.ts
  src/search.ts
  src/types.ts
  src/user.ts
  src/utils.ts
  tests/__snapshots__/help.test.ts.snap
  tests/battle.test.ts
  tests/handler.commands.test.ts
  tests/handler.components.test.ts
  tests/handler.partial.test.ts
  tests/help.test.ts
  tests/trade.test.ts
  update_commands.ts
  update_models.ts
Labels: feature

#232 add a quicker way to distribute stat points
  __snapshots__/update_commands.test.ts.snap
  i18n/en-US.json
  i18n/es-ES.json
  src/battle.ts
  src/interactions.ts
  tests/battle.test.ts
  tests/handler.commands.test.ts
  update_commands.ts
Labels: qol

#234 update es-ES
  __snapshots__/update_commands.test.ts.snap
  i18n/es-ES.json
Labels: i18n

#238 fix likeslist empty pages
  src/user.ts
  tests/gacha.test.ts
Labels: hotfix
