Repository ker0olos/fable, pull requests merged in 2023-09, with the labels that each got.

#241 deploy kv limit is still capped to 10
  db/addCharacter.ts
  db/addTokens.ts
  db/tradeCharacters.ts
  src/webhooks.ts
Labels: hotfix

#242 Qulity of Life
  __snapshots__/update_commands.test.ts.snap
  db/addCharacter.ts
  db/getInventory.ts
  db/mod.ts
  i18n/en-US.json
  i18n/es-ES.json
  src/gacha.ts
  src/help.ts
  src/interactions.ts
  src/merge.ts
  src/trade.ts
  src/user.ts
  tests/__snapshots__/help.test.ts.snap
  tests/__snapshots__/merge.test.ts.snap
  tests/__snapshots__/synthesis.test.ts.snap
  tests/gacha.test.ts
  tests/handler.commands.test.ts
  tests/handler.components.test.ts
  tests/merge.test.ts
  tests/trade.test.ts
  tests/user.test.ts
  update_commands.ts
Labels: hotfix, qol

#243 Hotfix
  __snapshots__/update_commands.test.ts.snap
  db/tradeCharacters.ts
  i18n/en-US.json
  i18n/es-ES.json
  tests/__snapshots__/help.test.ts.snap
Labels: hotfix

#244 Update es-ES.json
  __snapshots__/update_commands.test.ts.snap
  i18n/es-ES.json
Labels: i18n

#245 error proof merging a tiny bit
  db/addCharacter.ts
  db/tradeCharacters.ts
Labels: hotfix

#250 increase atomic ops
  db/addCharacter.ts
  db/mod.ts
  db/tradeCharacters.ts
  src/search.ts
  tests/discord.test.ts
  tests/gacha.test.ts
  update_topgg_stats.ts
Labels: hotfix

#253 store a voting ref in the database instead
  db/mod.ts
  db/voteRef.ts
  src/config.ts
  src/search.ts
  src/shop.ts
  src/user.ts
  src/utils.ts
  src/webhooks.ts
  tests/config.test.ts
  tests/discord.test.ts
  tests/gacha.test.ts
  tests/shop.test.ts
  tests/user.test.ts
  tests/utils.test.ts
  tests/webhooks.test.ts
  update_topgg_stats.ts
Labels: qol
